### ISSUE TITLE
Sample Project Doesnt build on 5.3?

### ISSUE THREAD

**Issue by OptimisticMonkey** [arnaud-jamin/Cog#3]
Cog-main\Source\CogSample\CogSampleLogCategories.h(3): error C2011: 'FLogCategoryLogCogAlways': 'struct' type redefinition

**Comment by OptimisticMonkey** [comment]
Looks like CogSampleLogCategories.h is just missing:    #pragma once

**Comment by OptimisticMonkey** [comment]
Other than that - really cool so far

**Comment by arnaud-jamin** [comment]
fixed thanks!
